apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-exporter
  template:
    metadata:
      labels:
        app: helm-exporter
    spec:
      serviceAccountName: k8s-101-role
      containers:
        - name: helm-exporter
          image: ticalma/helm-metrics-exporter:1.0
          ports:
            - containerPort: 2112
