apiVersion: v1
kind: Service
metadata:
  name: helm-exporter
  namespace: monitoring
  labels:
    app: helm-exporter
spec:
  ports:
  - port: 2112
    name: helm
    protocol: TCP
    targetPort: 2112
  selector:
    app: helm-exporter
  sessionAffinity: None
  type: ClusterIP
